console.log("script loaded");
const logos = [
  "AdaLogo.png",
  "AliceLogo.png",
  "ArtoriaLogo.png",
  "AshleyGravesLogo.png",
  "BlackfireLogo.png",
  "ChelLogo.png",
  "ChikaLogo.png",
  "DarknessLogo.png",
  "EmilyLogo.png",
  "EnaLogo.png",
  "ErzaLogo.png",
  "FernLogo.png",
  "FrierenLogo.png",
  "GoogleChanLogo.png",
  "GwenLogo.png",
  "HagakureTooruLogo.png",
  "HayasakaLogo.png",
  "HestiaLogo.png",
  "HinataKahoLogo.png",
  "HinataLogo.png",
  "KugisakiLogo.png",
  "LoonaLogo.png",
  "LucyHeartfiliaLogo.png",
  "LucyLogo.png",
  "MafuyuLogo.png",
  "MaiLogo.png",
  "MakimaLogo.png",
  "MeguminLogo.png",
  "MikuBrazilianLogo.png",
  "MikuLogo.png",
  "MinaLogo.png",
  "MirukoLogo.png",
  "NazunaLogo.png",
  "PomniLogo.png",
  "RaftaliaLogo.png",
  "RainbowDashLogo.png",
  "RavenLogo.png",
  "RebeccaLogo.png",
  "RemLogo.png",
  "RezeLogo.png",
  "RikkaLogo.png",
  "RinLogo.png",
  "RukoLogo.png",
  "RyuLionLogo.png",
  "SaberLogo.png",
  "SakurasoLogo.png",
  "SentoLogo.png",
  "ShegoLogo.png",
  "ShinobuLogo.png",
  "SnowLogo.png",
  "TamakiLogo.png",
  "TogaLogo.png",
  "TooruLogo.png",
  "WidowmakerLogo.png",
  "YokoLogo.png",
  "YorLogo.png",
  "YoruichiLogo.png",
  "ZeroTwoLogo.png",
  ];
const randomLogo = logos[Math.floor(Math.random() * logos.length)];





  
